export const ONBOARDING_CONSTANTS = {
  TOTAL_STEPS: 5,
  MIN_GOALS: 1,
  MAX_GOALS: 3,
  MIN_STEP: 0,
  MAX_STEP: 4,
  QUIZ_QUESTION_COUNT: 6,
  TRANSITION_DURATION_MS: 300,
  QUIZ_AUTO_ADVANCE_DELAY_MS: 400,
  GLOW_TRANSITION_MS: 200,
  PRESS_SCALE_DURATION_MS: 100,
} as const;
